version: "3"
services:
  hello_image_caption:
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #    image: ghcr.io/luler/hello_image_caption:latest
    image: ghcr.libcuda.so/luler/hello_image_caption:latest
    restart: always
    ports:
      - 2233:8000
    volumes:
      - .:/app